### ISSUE TITLE
Close connection, statement, and resultset for database

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-grant-loader#3]
Connection, statement, and resultset are all left open. Maybe refactor to support a close() option on CoeusConnector. Could also pass back `List` instead of `ResultSet` and close everything in a `finally` or `try with resources`, but that would obviously require loading all data into memory... probably ok for this amount of data, but I'll leave that up to you!

**Comment by jrmartino** [comment]
have changed the code to use try with resources on the connection, statement and ResultSet for the database. We now store the results in an intermediate data object to be processed by the GrantUpdater
